# conda environment name
name: study

# channels needed for bioconda
channels:
  - defaults
  - bioconda
  - conda-forge

# funpipe dependencies
dependencies:
# third party tools
  - samtools=1.9
  - bwa=0.7.8
# python libraries
  - pip:
    - numpy==1.15.4
    - pandas==0.23.4
    - matplotlib==3.0.2
    - seaborn==0.9.0
